from client_errorcondition import errorcondition
from client_machinemonitoring import machinemonitoring
from client_clouduserrole import clouduserrole
from client_resourcegroup import resourcegroup
from client_clouduser import clouduser
from client_lan import lan
from client_device import device
from client_job import job
from client_ipaddress import ipaddress
from client_drpdb import drpdb
from client_sso import sso
from client_networkzonerule import networkzonerule
from client_cmc import cmc
from client_customer import customer
from client_capacityplanning import capacityplanning
from client_networkzone import networkzone
from client_cable import cable
from client_rack import rack
from client_os import os
from client_datacenter import datacenter
from client_vdc import vdc
from client_dsspolicy import dsspolicy
from client_dssnamespace import dssnamespace
from client_disk import disk
from client_cloud import cloud
from client_cloudusergroup import cloudusergroup
from client_backplane import backplane
from client_application import application
from client_location import location
from client_policy import policy
from client_machine import machine
from client_cloudspace import cloudspace

from pylabs import q
from osis import init
init(q.system.fs.joinPaths(q.dirs.baseDir, 'libexec', 'osis'))