__author__ = 'racktivity'
__tags__ = 'wizard', 'location_create'
COUNTRIES = ['Afghanistan',
             'Albania',
             'Algeria',
             'American Samoa',
             'Andorra',
             'Angola',
             'Anguilla',
             'Antarctica',
             'Antigua and Barbuda',
             'Argentina',
             'Armenia',
             'Aruba',
             'Australia',
             'Austria',
             'Azerbaijan',
             'Bahamas',
             'Bahrain',
             'Bangladesh',
             'Barbados',
             'Belarus',
             'Belgium',
             'Belize',
             'Benin',
             'Bermuda',
             'Bhutan',
             'Bolivia',
             'Bosnia and Herzegovina',
             'Botswana',
             'Bouvet Island',
             'Brazil',
             'British Indian Ocean Territory',
             'British Virgin Islands',
             'Brunei Darussalam',
             'Bulgaria',
             'Burkina Faso',
             'Burundi',
             'Cambodia',
             'Cameroon',
             'Canada',
             'Cape Verde',
             'Cayman Islands',
             'Central African Republic',
             'Chad',
             'Chile',
             'China',
             'Christmas Island',
             'Cocos (Keeling) Islands',
             'Colombia',
             'Comoros',
             'Congo',
             'Cook Islands',
             'Costa Rica',
             "Cote d'Ivoire",
             'Croatia',
             'Cuba',
             'Cyprus',
             'Czech Republic',
             'Denmark',
             'Djibouti',
             'Dominica',
             'Dominican Republic',
             'Ecuador',
             'Egypt',
             'El Salvador',
             'Equatorial Guinea',
             'Eritrea',
             'Estonia',
             'Ethiopia',
             'Falkland Islands',
             'Faroe Islands',
             'Fiji',
             'Finland',
             'France',
             'French Guiana',
             'French Polynesia',
             'French Southern Territories',
             'Gabon',
             'Gambia',
             'Georgia',
             'Germany',
             'Ghana',
             'Gibraltar',
             'Greece',
             'Greenland',
             'Grenada',
             'Guadeloupe',
             'Guam',
             'Guatemala',
             'Guernsey',
             'Guinea',
             'Guinea-Bissau',
             'Guyana',
             'Haiti',
             'Heard Island and McDonald Islands',
             'Holy See',
             'Honduras',
             'Hong Kong',
             'Hungary',
             'Iceland',
             'India',
             'Indonesia',
             'Iran',
             'Iraq',
             'Ireland',
             'Isle of Man',
             'Israel',
             'Italy',
             'Jamaica',
             'Japan',
             'Jersey',
             'Jordan',
             'Kazakhstan',
             'Kenya',
             'Kiribati',
             'Korea',
             'Kuwait',
             "Lao People's Democratic Republic",
             'Latvia',
             'Lesotho',
             'Liberia',
             'Liechten',
             'Lithuania',
             'Luxembourg',
             'Macedonia',
             'Madagascar',
             'Malaysia',
             'Maldives',
             'Malta',
             'Marshall Islands',
             'Martinique',
             'Mau',
             'Mauritius',
             'Mayotte',
             'Mexico',
             'Moldova',
             'Monaco',
             'Mongol',
             'Montenegro',
             'Montser',
             'Morocco',
             'Mozambique',
             'Myanmar',
             'Nauru',
             'Ne',
             'Netherlands Antilles',
             'New Caledonia',
             'Nicaragua',
             'Niger',
             'Nigeria',
             'Niue',
             'Norfolk Island',
             'North',
             'Norway',
             'Oman',
             'Palau',
             'Panama',
             'Paragu',
             'Peru',
             'Philippines',
             'Pitcairn Islands',
             'Portugal',
             'Puerto',
             'Qatar',
             'Romania',
             'Russian Federation',
             'Rwanda',
             'Saint Helena',
             'Saint Kitts and Nevis',
             'Saint Martin',
             'Saint Vincen',
             'Samoa',
             'San Marino',
             'Sao Tome and Principe',
             'Senegal',
             'Serbia',
             'Seychelles',
             'Sierra Leone',
             'Singapore',
             'Slovenia',
             'Solomon Islands',
             'South Africa',
             'South Georgia and the So',
             'Spain',
             'Sudan',
             'Suriname',
             'Svalbard & Jan Mayen Islands',
             'Swaziland',
             'Sweden',
             'Syrian Arab Republic',
             'Taiwan',
             'Tajikistan',
             'Tanzania',
             'Thailand',
             'Timor-Leste',
             'To',
             'Togo',
             'Tokelau',
             'Trinidad and Tobago',
             'Tunisia',
             'Turkey',
             'Turkmenistan',
             'Tuvalu',
             'Ukraine',
             'United Arab Emirates',
             'United Kingdom',
             'United States Minor Outlyin',
             'United States Virgin I',
             'United States of America',
             'Uruguay',
             'Uzbekistan',
             'Venezuela',
             'Vietnam',
             'Wallis and Futuna',
             'Yemen',
             'Zambia',
             'Zimbabwe',
             'land Islands']

def getTagString(q, tab):
    labels = None
    labelsvalue = tab.elements['labels'].value
    trim = lambda s: s.strip()
    if labelsvalue:
        labels = set(map(trim, labelsvalue.split(',')))

    tags = dict()
    tagsvalue = tab.elements['tags'].value
    if tagsvalue:
        for tag in map(trim, tagsvalue.split(',')):
            tagslist = tag.split(':')
            tags[tagslist[0].strip()] = tagslist[1].strip()
    return q.base.tags.getTagString(labels, tags)

def main(q, i, p, params, tags):
    cloudapi = p.api.action.racktivity

    locationform = q.gui.form.createForm()
    locationtab = locationform.addTab('location', 'Create Campus')
    locationtab.addText('name', 'Name', optional=False)
    locationtab.addMultiline('description', 'Description')
    locationtab.addText('alias', 'Alias')
    locationtab.addText('address', 'Address')
    locationtab.addText('city', 'City')
    locationtab.addChoice("country", "Country", dict(enumerate(COUNTRIES)))
    locationtab.addText("latitude", "Latitude", validator="^\d*(\.\d+)?$")
    locationtab.addText("longitude", "Longitude", validator="^\d*(\.\d+)?$")
    locationtab.addYesNo('public', 'Is Public location', selectedValue=0)
    locationtab.addText('tags', 'Tags', helpText='Enter tags in the form of tag1:value1,tag2:value2')
    locationtab.addText('labels', 'Labels', helpText='Enter labels as comma separated values e.g. label1,label2')
    locationform.loadForm(q.gui.dialog.askForm(locationform))
    locationtab = locationform.tabs['location']
    tagstring = getTagString(q, locationtab)
    
    lat = locationtab.elements['latitude'].value or 0.0
    long = locationtab.elements['longitude'].value or 0.0
    
    returnedvalue = cloudapi.location.create(name=locationtab.elements['name'].value,
                                                 description=locationtab.elements['description'].value,
                                                 alias=locationtab.elements['alias'].value,
                                                 address=locationtab.elements['address'].value,
                                                 city=locationtab.elements['city'].value,
                                                 country=COUNTRIES[int(locationtab.elements['country'].value)],
                                                 coordinatesinfo={'latitude': float(lat),
                                                                  'longitude': float(long)},
                                                 tags=tagstring,
                                                 public=True if locationtab.elements['public'].value=='Yes' else False)
    
    q.gui.dialog.showMessageBox('Location "%s" is being created' % locationtab.elements['name'].value, "Create Campus")

def main(q, i, p, params, tags):
    return True