__tags__ = "wizard", "customer_create"
__author__ = "racktivity"


COUNTRIES = ['Afghanistan',
             'Albania',
             'Algeria',
             'American Samoa',
             'Andorra',
             'Angola',
             'Anguilla',
             'Antarctica',
             'Antigua and Barbuda',
             'Argentina',
             'Armenia',
             'Aruba',
             'Australia',
             'Austria',
             'Azerbaijan',
             'Bahamas',
             'Bahrain',
             'Bangladesh',
             'Barbados',
             'Belarus',
             'Belgium',
             'Belize',
             'Benin',
             'Bermuda',
             'Bhutan',
             'Bolivia',
             'Bosnia and Herzegovina',
             'Botswana',
             'Bouvet Island',
             'Brazil',
             'British Indian Ocean Territory',
             'British Virgin Islands',
             'Brunei Darussalam',
             'Bulgaria',
             'Burkina Faso',
             'Burundi',
             'Cambodia',
             'Cameroon',
             'Canada',
             'Cape Verde',
             'Cayman Islands',
             'Central African Republic',
             'Chad',
             'Chile',
             'China',
             'Christmas Island',
             'Cocos (Keeling) Islands',
             'Colombia',
             'Comoros',
             'Congo',
             'Cook Islands',
             'Costa Rica',
             "Cote d'Ivoire",
             'Croatia',
             'Cuba',
             'Cyprus',
             'Czech Republic',
             'Denmark',
             'Djibouti',
             'Dominica',
             'Dominican Republic',
             'Ecuador',
             'Egypt',
             'El Salvador',
             'Equatorial Guinea',
             'Eritrea',
             'Estonia',
             'Ethiopia',
             'Falkland Islands',
             'Faroe Islands',
             'Fiji',
             'Finland',
             'France',
             'French Guiana',
             'French Polynesia',
             'French Southern Territories',
             'Gabon',
             'Gambia',
             'Georgia',
             'Germany',
             'Ghana',
             'Gibraltar',
             'Greece',
             'Greenland',
             'Grenada',
             'Guadeloupe',
             'Guam',
             'Guatemala',
             'Guernsey',
             'Guinea',
             'Guinea-Bissau',
             'Guyana',
             'Haiti',
             'Heard Island and McDonald Islands',
             'Holy See',
             'Honduras',
             'Hong Kong',
             'Hungary',
             'Iceland',
             'India',
             'Indonesia',
             'Iran',
             'Iraq',
             'Ireland',
             'Isle of Man',
             'Israel',
             'Italy',
             'Jamaica',
             'Japan',
             'Jersey',
             'Jordan',
             'Kazakhstan',
             'Kenya',
             'Kiribati',
             'Korea',
             'Kuwait',
             "Lao People's Democratic Republic",
             'Latvia',
             'Lesotho',
             'Liberia',
             'Liechten',
             'Lithuania',
             'Luxembourg',
             'Macedonia',
             'Madagascar',
             'Malaysia',
             'Maldives',
             'Malta',
             'Marshall Islands',
             'Martinique',
             'Mau',
             'Mauritius',
             'Mayotte',
             'Mexico',
             'Moldova',
             'Monaco',
             'Mongol',
             'Montenegro',
             'Montser',
             'Morocco',
             'Mozambique',
             'Myanmar',
             'Nauru',
             'Ne',
             'Netherlands Antilles',
             'New Caledonia',
             'Nicaragua',
             'Niger',
             'Nigeria',
             'Niue',
             'Norfolk Island',
             'North',
             'Norway',
             'Oman',
             'Palau',
             'Panama',
             'Paragu',
             'Peru',
             'Philippines',
             'Pitcairn Islands',
             'Portugal',
             'Puerto',
             'Qatar',
             'Romania',
             'Russian Federation',
             'Rwanda',
             'Saint Helena',
             'Saint Kitts and Nevis',
             'Saint Martin',
             'Saint Vincen',
             'Samoa',
             'San Marino',
             'Sao Tome and Principe',
             'Senegal',
             'Serbia',
             'Seychelles',
             'Sierra Leone',
             'Singapore',
             'Slovenia',
             'Solomon Islands',
             'South Africa',
             'South Georgia and the So',
             'Spain',
             'Sudan',
             'Suriname',
             'Svalbard & Jan Mayen Islands',
             'Swaziland',
             'Sweden',
             'Syrian Arab Republic',
             'Taiwan',
             'Tajikistan',
             'Tanzania',
             'Thailand',
             'Timor-Leste',
             'To',
             'Togo',
             'Tokelau',
             'Trinidad and Tobago',
             'Tunisia',
             'Turkey',
             'Turkmenistan',
             'Tuvalu',
             'Ukraine',
             'United Arab Emirates',
             'United Kingdom',
             'United States Minor Outlyin',
             'United States Virgin I',
             'United States of America',
             'Uruguay',
             'Uzbekistan',
             'Venezuela',
             'Vietnam',
             'Wallis and Futuna',
             'Yemen',
             'Zambia',
             'Zimbabwe',
             'land Islands']

def main(q,i,params,tags):
    cloudApi = i.config.cloudApiConnection.find('main')
    form = q.gui.form.createForm()
    
    tab = form.addTab("main", "Create Customer")
    tab.addText("custName", "Name", optional=False)
    tab.addMultiline("custDescription", "Description")
    tab.addText("custAddress", "Address", optional=False)
    tab.addText("custCity", "City", optional=False)
    tab.addChoice("custCountry", "Country", dict(enumerate(COUNTRIES)))
    
    valid = False
    while not valid:
        form.loadForm(q.gui.dialog.askForm(form))
        #validate data
        tab = form.tabs['main']
        username = tab.elements['custName'].value
        if cloudApi.customer.find(name = username)['result']['guidlist']:
            tab.elements['custName'].message = "Customer with the same name already exists"
            tab.elements['custName'].status = "error"
        else:
            valid = True
    tab = form.tabs['main']
    cloudApi.customer.create(name=tab.elements['custName'].value,
                            description=tab.elements['custDescription'].value,
                            address=tab.elements['custAddress'].value,
                            city=tab.elements['custCity'].value,
                            country=COUNTRIES[int(tab.elements['custCountry'].value)])
    
    q.gui.dialog.showMessageBox("Customer '%s' is being created" % tab.elements['custName'].value, "Create Customer")
    
def match(q,i,params,tags):
    return True