#!/bin/bash
. /opt/qbase5/bin/init-bootstrap.sh

if [ "x$IPYTHONDIR" == "x" ]; then
  export IPYTHONDIR=$HOME/.ipython
fi

mkdir -p $IPYTHONDIR

mkdir -p $base/var/pid
mkdir -p $base/var/log
mkdir -p $base/var/tmp

python $base/utils/shell.py "$1" "$2" "$3" "$4"


    
