#!/bin/bash
find $1 -name 'Test*.py'|while read fn
do
        header=`echo $fn|grep -o '[^/]*/[^/]*$'`
	echo "<H2>$header</H2>"
	echo "<TABLE border=1>"
	echo "<TR><TD><B>Function</B></TD><TD><B>Description</B></TD<TD><B>Expected Result</B></TD><TD><B>Command</B></TD></TR>"
	grep '^ *@description\|^ *@expected_result\|^ *@params\|()' "$fn"|while read line
	do
		line=`echo $line|sed 's/^ *//'`
		if [[ $line == @description* ]]
		then
			desc=`echo $line|sed 's/@description *://'`
		elif [[ "$line" == @expected_result* ]]
		then
			cmd=`echo $line|sed 's/@expected_result *://'`
			echo "<TR><TD>$func</TD><TD>$desc</TD><TD> $cmd</TD><TD>$params</TD></TR>"
		elif [[ "$line" == @params* ]]
		then
			params=`echo $line|sed 's/@params *://'`
		else
			func=`echo $line|grep -o '[^ ]*()'`
		fi
	done
	echo "</TABLE><BR>"
done

